### ISSUE TITLE
[构建失败] python-mako

### ISSUE THREAD

**Issue by jiewu-plct** [isrc-cas/tarsier-oerv#230]
````
[ 1228s] ________________ ERROR collecting test/ext/test_linguaplugin.py ________________
[ 1228s] Traceback (most recent call last):
[ 1228s]   File "/usr/lib/python3.7/site-packages/py/_path/local.py", line 668, in pyimport
[ 1228s]     __import__(modname)
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/test/__init__.py", line 10, in <module>
[ 1228s]     from mako.template import Template
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/template.py", line 20, in <module>
[ 1228s]     from mako import codegen
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/codegen.py", line 17, in <module>
[ 1228s]     from mako import filters
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/filters.py", line 40, in <module>
[ 1228s]     import markupsafe
[ 1228s]   File "/usr/lib64/python3.7/site-packages/markupsafe/__init__.py", line 13, in <module>
[ 1228s]     from collections import Mapping
[ 1228s]   File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
[ 1228s]   File "/usr/lib64/python3.7/collections/__init__.py", line 52, in __getattr__
[ 1228s]     DeprecationWarning, stacklevel=2)
[ 1228s] DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
[ 1228s] _____________________ ERROR collecting test/foo/test_ns.py _____________________
[ 1228s] Traceback (most recent call last):
[ 1228s]   File "/usr/lib/python3.7/site-packages/py/_path/local.py", line 668, in pyimport
[ 1228s]     __import__(modname)
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/test/__init__.py", line 10, in <module>
[ 1228s]     from mako.template import Template
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/template.py", line 20, in <module>
[ 1228s]     from mako import codegen
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/codegen.py", line 17, in <module>
[ 1228s]     from mako import filters
[ 1228s]   File "/home/abuild/rpmbuild/BUILD/Mako-1.1.4/mako/filters.py", line 40, in <module>
[ 1228s]     import markupsafe
[ 1228s]   File "/usr/lib64/python3.7/site-packages/markupsafe/__init__.py", line 13, in <module>
[ 1228s]     from collections import Mapping
[ 1228s]   File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
[ 1228s]   File "/usr/lib64/python3.7/collections/__init__.py", line 52, in __getattr__
[ 1228s]     DeprecationWarning, stacklevel=2)
[ 1228s] DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
[ 1228s] !!!!!!!!!!!!!!!!!!! Interrupted: 23 errors during collection !!!!!!!!!!!!!!!!!!!
[ 1228s] ============================== 23 errors in 7.67s ==============================
[ 1228s] error: Bad exit status from /var/tmp/rpm-tmp.8BgILK (%check)
[ 1228s] 
[ 1228s] 
[ 1228s] RPM build errors:
[ 1228s]     Bad exit status from /var/tmp/rpm-tmp.8BgILK (%check)
[ 1229s] 
[ 1229s] oe-RISCV-worker54-home failed "build python-mako.spec" at Sat Jan  8 15:25:04 UTC 2022.
[ 1229s] 
````
有多达23个错误都是类似的由于依赖包python3-markupsafe的版本的问题导致的错误，需要等python3-markupsafe升级后才能构建python-mako

**Comment by xijing21** [comment]
![image](https://user-images.githubusercontent.com/84754181/181232622-78ee9c3b-2974-45f3-a0b0-062425e85382.png)
构建成功，关闭：https://build.tarsier-infra.com/package/show/openEuler:22.03/python-mako
