### ISSUE TITLE
在 oe rv64 系统中测试 DaCapo Benchmarks

### ISSUE THREAD

**Issue by BigBrotherJu** [isrc-cas/tarsier-oerv#237]
DaCapo Benchmarks 的官网是 [http://dacapo-bench.org/](http://dacapo-bench.org/)，另外好像还有一个老的官网 [http://dacapobench.sourceforge.net/](http://dacapobench.sourceforge.net/)。根据新官网的消息，目前最新的 release 在 [sourceforge](https://sourceforge.net/projects/dacapobench/files/9.12-bach-MR1/) 上下载，下载得到 `dacapo-9.12-MR1-bach.jar`：

> Jan 12, 2018 We made a maintenance release of the benchmark suite. This is the first full release in a number of years, and fixes a handful of issues with the suite, without changing the existing benchmarks. Major changes are listed here. In short, the source distribution should now build correctly (broken URLs fixed), the suite should run fine on Java 8 JVMs (with the exception of tomcat which has an underlying problem unrelated to DaCapo, and we have added a new benchmark, lusearch-fix, which is identical to lusearch except that a one-line bug fix to lucene has been applied (we recommend lusearch-fix over lusearch). The issue with lusearch is described in this paper.

这段话中还提到这个 benchmark suite 可以在 Java 8 JVM 上运行，那 11 行不行？会不会又出现版本问题？

和这个 release 有关的 [release note](https://github.com/dacapobench/dacapobench/blob/master/benchmarks/RELEASE_NOTES.txt) 在他们的 GitHub 仓库中，其中提到了如何运行这个 jar 文件：

```
2.2 Running

  o It is essential that you read and observe the usage guidelines
    that appear in README.md

  o Run a benchmark:
      java -jar <dacapo-jar-name>.jar <benchmark>

  o For usage information, run with no arguments.
```

**Comment by BigBrotherJu** [comment]
首先，我们尝试在 fedora 35 中运行 DaCapo Benchmarks：

``` console
[juhan@fedora java-test]$ java -jar dacapo-9.12-MR1-bach.jar
usage: DaCapo Benchmark suite
 -c,--callback <callback>                     Use class <callback> to
                                              bracket benchmark runs
 -C,--converge                                Allow benchmark times to
                                              converge before timing
 -d,--debug                                   Verbose debugging
                                              information
 -f,--timeout-dialation <timeout_dialation>   Set the time dialation of
                                              the timeouts in the
                                              benchmark by the given
                                              integer factor.
 -h,--help                                    Print this help
 -i,--information                             Display benchmark
                                              information
    --ignore-validation                       Don't halt on validation
                                              failure
 -k,--thread-factor <thread_per_cpu>          Set the number of threads
                                              per CPU to drive the
                                              workload (mutually exclusive
                                              with -t)
 -l,--list-benchmarks                         List available benchmarks
    --max-iterations <max_iterations>         Run a max of
                                              <max_iterations> iterations
                                              (default 20)
 -n,--iterations <iter>                       Run the benchmark <iter>
                                              times
    --no-digest-output                        Turn off SHA1 digest of
                                              stdout/stderr
    --no-pre-iteration-gc                     Skip performing System.gc()
                                              before the start of each
                                              iteration
    --no-validation                           Don't validate at all
    --preserve                                Preserve output files
                                              (debug)
 -r,--release-notes                           Print the release notes
 -s,--size <SIZE>                             Size of input data
    --scratch-directory <dir>                 Specify an alternate scratch
                                              directory <dir>
    --sizes                                   Report the valid sizes for
                                              the specified benchmarks
 -t,--thread-count <thread_count>             Set the thread count to
                                              drive the workload (mutually
                                              exclusive -k)
 -v,--verbose                                 Verbose output
    --validation-report <report_file>         Report digests, line counts
                                              etc
    --variance <pct>                          Target coefficient of
                                              variation <pct> (default
                                              3.0)
    --window <window>                         Measure variance over
                                              <window> runs (default 3)
```

用 `-l` 列出所有 benchmark，然后我们挑一个运行：

``` console
[juhan@fedora java-test]$ java -jar dacapo-9.12-MR1-bach.jar -l
avrora batik eclipse fop h2 jython luindex lusearch lusearch-fix pmd sunflow tomcat tradebeans tradesoap xalan
[juhan@fedora java-test]$ java -jar dacapo-9.12-MR1-bach.jar avrora
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 5955 msec =====
```

看起来，fedora 的 OpenJDK 11 好像没问题。

**Comment by BigBrotherJu** [comment]
用 scp 把 `dacapo-9.12-MR1-bach.jar` 传到 oe rv 中，然后同样运行 avrora benchmark：

``` console
[root@openEuler-RISCV-rare dacapo]# java -jar dacapo-9.12-MR1-bach.jar avrora
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 234920 msec =====
```

可以成功运行，看来 oe rv 中的 openjdk 11 也没什么问题，就是花的时间是 fedora 的 20 倍左右。

**Comment by lazyparser** [comment]
good

一般我们使用对比验证：

1. 一个 benchmark A 在 amd64 平台上的软件 B 运行，得到一个基线（baseline）
2. 在 RV64GC 平台上运行 B + A，看看是否有错误。有错误的话，开新的issue，有可能是有bug需要fix
3. 在RISC-V平台上，软件B具有一定的特殊性：可能同时有多个版本： B--（没有JIT）、B-（有baseline JIT）、B+ 针对某一个CPU/平台进行了优化。

在上述过车个闹钟功能，运行的java，看一下 `java -version` 内容，有可能是用的是 zero 解释器模式。

接下来可以尝试使用 BishengJDK 的带有 JIT 的版本，速度可能会有至少10倍以上的提升。

**Comment by BigBrotherJu** [comment]
接下来，我们进行正式测试。我们首先在 amd64 的 fedora 35 上运行 DaCapo 的所有 benchmark。fedora 35 是运行在 MacBook Pro 2018 15 寸上的虚拟机，被分配了 4G 内存和 2 个 CPU。MacBook Pro 2018 15 寸本身的 CPU 是 i7-8750H，6 核 12 线程，内存一共 16 G。fedora 35 上的 jdk 如下所示：

``` console
[juhan@fedora dacapo]$ java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)
```

首先列出所有 benchmark：

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar -l
avrora batik eclipse fop h2 jython luindex lusearch lusearch-fix pmd sunflow tomcat tradebeans tradesoap xalan
```

这些 benchmark 在[老官网](http://dacapobench.sourceforge.net/benchmarks.html)上有介绍：

Benchmark | What does it do
:- | :-
avrora | simulates a number of programs run on a grid of AVR microcontrollers
batik | produces a number of Scalable Vector Graphics (SVG) images based on the unit tests in Apache Batik
eclipse | executes some of the (non-gui) jdt performance tests for the Eclipse IDE
fop | takes an XSL-FO file, parses it and formats it, generating a PDF file.
h2 | executes a JDBCbench-like in-memory benchmark, executing a number of transactions against a model of a banking application, replacing the hsqldb benchmark
jython | inteprets a the pybench Python benchmark
luindex | Uses lucene to indexes a set of documents; the works of Shakespeare and the King James Bible
lusearch | Uses lucene to do a text search of keywords over a corpus of data comprising the works of Shakespeare and the King James Bible
pmd | analyzes a set of Java classes for a range of source code problems
sunflow | renders a set of images using ray tracing
tomcat | runs a set of queries against a Tomcat server retrieving and verifying the resulting webpages
tradebeans | runs the daytrader benchmark via a Jave Beans to a GERONIMO backend with an in memory h2 as the underlying database
tradesoap | runs the daytrader benchmark via a SOAP to a GERONIMO backend with in memory h2 as the underlying database
xalan | transforms XML documents into HTML

其中 lusearch-fix 在 [release note](https://github.com/dacapobench/dacapobench/blob/6cf03808b686896eb092c038d6add7d9384f03f5/benchmarks/RELEASE_NOTES.txt#L95-L102) 中有介绍：

> lusearch-fix is introduced as a new benchmark.   The lusearch-fix
              and lusearch benchmarks differ by a single line of code.   This
	      is a bug fix to lucene, which dramatically changes the performance of
	      lusearch, reducing the amount of allocation greatly.
	      		https://issues.apache.org/jira/browse/LUCENE-1800
			https://dl.acm.org/citation.cfm?id=2048092
	      We encourage you to use lusearch-fix in place of lusearch.   We
	      retain the unpatched lusearch in this release for historical consistency.

接下来我们每个 benchmark 都运行一遍，如果有出错先不管。出错的 benchmark 有：batik，eclipse，tomcat。

avrora:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar avrora
===== DaCapo 9.12-MR1 avrora starting =====
===== DaCapo 9.12-MR1 avrora PASSED in 5591 msec =====
```

batik:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar batik
===== DaCapo 9.12-MR1 batik starting =====
About to transcode 3 SVG file(s)

Converting mapWaadt.svg to /home/juhan/local/java-test/dacapo/./scratch/mapWaadt.png ... ... success
Converting mapSpain.svg to /home/juhan/local/java-test/dacapo/./scratch/mapSpain.png ... ... success
Converting sydney.svg to /home/juhan/local/java-test/dacapo/./scratch/sydney.png ... java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Batik.iterate(Batik.java:41)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/TruncatedFileException
	at org.apache.batik.ext.awt.image.codec.jpeg.JPEGRegistryEntry.handleStream(JPEGRegistryEntry.java:87)
	at org.apache.batik.ext.awt.image.spi.ImageTagRegistry.readURL(ImageTagRegistry.java:189)
	at org.apache.batik.bridge.SVGImageElementBridge.createImageGraphicsNode(SVGImageElementBridge.java:257)
	at org.apache.batik.bridge.SVGImageElementBridge.buildImageGraphicsNode(SVGImageElementBridge.java:176)
	at org.apache.batik.bridge.SVGImageElementBridge.createGraphicsNode(SVGImageElementBridge.java:118)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:212)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:78)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:214)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:159)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:992)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:715)
	at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.TruncatedFileException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.dacapo.harness.DacapoClassLoader.loadClass(DacapoClassLoader.java:123)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 30 more
```

eclipse:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar eclipse
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.internal.baseadaptor.BaseStorage (file:/home/juhan/local/java-test/dacapo/./scratch/jar/eclipse.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.baseadaptor.BaseStorage
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Eclipse.preIteration(Eclipse.java:54)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:171)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:74)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
	... 13 more
===== DaCapo 9.12-MR1 eclipse starting =====
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Eclipse.iterate(Eclipse.java:65)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.reStart(EclipseAppLauncher.java:157)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:370)
	... 13 more
Digest validation failed for stdout.log, expecting 0x883c142aebf68c13c630dae7dcc488b32d565e3d found 0xda39a3ee5e6b4b0d3255bfef95601890afd80709
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x5ff19a7a0df7b784d6f87b779206477ed70a442e
===== DaCapo 9.12-MR1 eclipse FAILED =====
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Eclipse.postIteration(Eclipse.java:74)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:198)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.reStart(EclipseAppLauncher.java:157)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:370)
	... 13 more
Validation FAILED for eclipse default
```

fop:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar fop
===== DaCapo 9.12-MR1 fop starting =====
===== DaCapo 9.12-MR1 fop PASSED in 1607 msec =====
```

h2:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar h2
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,4000]
===== DaCapo 9.12-MR1 h2 starting =====
....
Completed 4000 transactions
	Stock level .............   155 ( 3.9%)
	Order status by name ....   108 ( 2.7%)
	Order status by ID ......    65 ( 1.6%)
	Payment by name .........  1050 (26.2%)
	Payment by ID ...........   661 (16.5%)
	Delivery schedule .......   167 ( 4.2%)
	New order ...............  1774 (44.4%)
	New order rollback ......    20 ( 0.5%)
Resetting database to initial state
===== DaCapo 9.12-MR1 h2 PASSED in 3968 msec =====
```

jython:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar jython
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.common.base.internal.Finalizer (file:/home/juhan/local/java-test/dacapo/./scratch/jar/guava-r07.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of com.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
===== DaCapo 9.12-MR1 jython starting =====
-------------------------------------------------------------------------------
PYBENCH 2.0
-------------------------------------------------------------------------------
* using Python 2.5.2
* system check interval set to maximum: 2147483647
* using timer: time.time

Calibrating tests. Please wait...

Running 1 round(s) of the suite at warp factor 20:

* Round 1 done in 4.471 seconds.

-------------------------------------------------------------------------------
Benchmark: 2022-01-21 12:55:43
-------------------------------------------------------------------------------

    Rounds: 1
    Warp:   20
    Timer:  time.time

Test                             minimum  average  operation  overhead
-------------------------------------------------------------------------------
          BuiltinFunctionCalls:     70ms     70ms    0.27us    0.000ms
           BuiltinMethodLookup:     98ms     98ms    0.19us    0.000ms
                 CompareFloats:     61ms     61ms    0.10us    0.000ms
         CompareFloatsIntegers:     55ms     55ms    0.12us    0.000ms
               CompareIntegers:     85ms     85ms    0.09us    0.000ms
        CompareInternedStrings:    123ms    123ms    0.16us    0.000ms
                  CompareLongs:     53ms     53ms    0.10us    0.000ms
                CompareStrings:     79ms     79ms    0.16us    0.000ms
                CompareUnicode:     60ms     60ms    0.16us    0.000ms
                 ConcatStrings:     89ms     89ms    0.36us    0.000ms
                 ConcatUnicode:     34ms     34ms    0.23us    0.000ms
               CreateInstances:     53ms     53ms    0.95us    0.000ms
            CreateNewInstances:     79ms     79ms    1.88us    0.000ms
       CreateStringsWithConcat:     89ms     89ms    0.18us    0.000ms
       CreateUnicodeWithConcat:     52ms     52ms    0.26us    0.000ms
                  DictCreation:     77ms     77ms    0.38us    0.000ms
             DictWithFloatKeys:     59ms     59ms    0.13us    0.000ms
           DictWithIntegerKeys:     76ms     76ms    0.13us    0.000ms
            DictWithStringKeys:     77ms     77ms    0.13us    0.000ms
                      ForLoops:     57ms     57ms    4.56us    0.000ms
                    IfThenElse:    149ms    149ms    0.22us    0.000ms
                   ListSlicing:     23ms     23ms    3.29us    0.000ms
                NestedForLoops:     47ms     47ms    0.06us    0.000ms
          NormalClassAttribute:     90ms     90ms    0.15us    0.000ms
       NormalInstanceAttribute:     99ms     99ms    0.17us    0.000ms
           PythonFunctionCalls:     63ms     63ms    0.38us    0.000ms
             PythonMethodCalls:     46ms     46ms    0.41us    0.000ms
                     Recursion:     37ms     37ms    1.48us    0.000ms
                  SecondImport:     42ms     42ms    0.84us    0.000ms
           SecondPackageImport:     43ms     43ms    0.86us    0.000ms
         SecondSubmoduleImport:     68ms     68ms    1.36us    0.000ms
       SimpleComplexArithmetic:     91ms     91ms    0.21us    0.000ms
        SimpleDictManipulation:     83ms     83ms    0.14us    0.000ms
         SimpleFloatArithmetic:    122ms    122ms    0.18us    0.000ms
      SimpleIntFloatArithmetic:    119ms    119ms    0.18us    0.000ms
       SimpleIntegerArithmetic:    114ms    114ms    0.17us    0.000ms
        SimpleListManipulation:     89ms     89ms    0.15us    0.000ms
          SimpleLongArithmetic:     77ms     77ms    0.23us    0.000ms
                    SmallLists:     86ms     86ms    0.25us    0.000ms
                   SmallTuples:    174ms    174ms    0.64us    0.000ms
         SpecialClassAttribute:     89ms     89ms    0.15us    0.000ms
      SpecialInstanceAttribute:     86ms     86ms    0.14us    0.000ms
                StringMappings:    119ms    119ms    0.94us    0.000ms
              StringPredicates:    108ms    108ms    0.31us    0.000ms
                 StringSlicing:     52ms     52ms    0.19us    0.000ms
                     TryExcept:     14ms     14ms    0.01us    0.000ms
                TryRaiseExcept:    167ms    167ms    5.22us    0.000ms
                  TupleSlicing:     32ms     32ms    0.24us    0.000ms
               UnicodeMappings:    186ms    186ms   10.33us    0.000ms
             UnicodePredicates:     92ms     92ms    0.34us    0.000ms
             UnicodeProperties:    358ms    358ms    1.79us    0.000ms
                UnicodeSlicing:     80ms     80ms    0.33us    0.000ms
-------------------------------------------------------------------------------
Totals:                           4471ms   4471ms

===== DaCapo 9.12-MR1 jython PASSED in 7340 msec =====
```

luindex:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar luindex
===== DaCapo 9.12-MR1 luindex starting =====
===== DaCapo 9.12-MR1 luindex PASSED in 1240 msec =====
```

lusearch-fix:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar lusearch-fix
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,64]
===== DaCapo 9.12-MR1 lusearch-fix starting =====
4 query batches completed
8 query batches completed
12 query batches completed
16 query batches completed
20 query batches completed
24 query batches completed
28 query batches completed
32 query batches completed
36 query batches completed
40 query batches completed
44 query batches completed
48 query batches completed
52 query batches completed
56 query batches completed
60 query batches completed
64 query batches completed
===== DaCapo 9.12-MR1 lusearch-fix PASSED in 2760 msec =====
```

pmd:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar pmd
===== DaCapo 9.12-MR1 pmd starting =====
===== DaCapo 9.12-MR1 pmd PASSED in 2540 msec =====
```

sunflow:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar sunflow
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,256]
===== DaCapo 9.12-MR1 sunflow starting =====
===== DaCapo 9.12-MR1 sunflow PASSED in 4067 msec =====
```

tomcat:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar tomcat
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,64]
Server thread created
===== DaCapo 9.12-MR1 tomcat starting =====
Loading web application
Creating client threads
Waiting for clients to complete
URL /examples/jsp/jsp2/el/basic-arithmetic.jsp returned status 500 (expected 200)
# 输出中有很多类似 URL /examples/jsp/jsp2/el/basic-arithmetic.jsp returned status 500 (expected 200) 的结果，这里省略
URL /examples/jsp/tagplugin/choose.jsp returned status 500 (expected 200)
Client threads complete ... unloading web application
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x605fb82d919662f66ee72d25519bbf0c6ee3bf1d
===== DaCapo 9.12-MR1 tomcat FAILED =====
Server stopped ... iteration complete
Validation FAILED for tomcat default
```

tradebeans:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar tradebeans
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,512]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/home/juhan/local/java-test/dacapo/scratch/geronimo-jetty6-minimal-2.1.4/repository/com/sun/xml/bind/jaxb-impl/2.0.5/jaxb-impl-2.0.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Booting Geronimo Kernel (in Java 11.0.13)...
Geronimo startup complete
Successfully created tables
===== DaCapo 9.12-MR1 tradebeans starting =====
Resetting database and populating with 1098 stocks...
Populating database with 768 users...
Finished repopulating database
Running 512 trade sessions directly on server
Completed 512 trade sessions comprising 8862 trader actions
	Home ....................  1653 (18.7%)
	Portfolio ...............   738 ( 8.3%)
	Quote ...................  3758 (42.4%)
	Buy .....................   726 ( 8.2%)
	Sell ....................   761 ( 8.6%)
	Update ..................   126 ( 1.4%)
	Register ................    38 ( 0.4%)
	Login ...................   512 ( 5.8%)
	Logout ..................   550 ( 6.2%)
===== DaCapo 9.12-MR1 tradebeans PASSED in 6102 msec =====
Shutting down Geronimo...
```

tradesoap:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar tradesoap
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,128]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/home/juhan/local/java-test/dacapo/scratch/geronimo-jetty6-minimal-2.1.4/repository/com/sun/xml/bind/jaxb-impl/2.0.5/jaxb-impl-2.0.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Booting Geronimo Kernel (in Java 11.0.13)...
Geronimo startup complete
Successfully created tables
===== DaCapo 9.12-MR1 tradesoap starting =====
Resetting database and populating with 1098 stocks...
Populating database with 192 users...
Finished repopulating database
Running 128 trade sessions from client via soap
Completed 128 trade sessions comprising 2280 trader actions
	Home ....................   447 (19.6%)
	Portfolio ...............   173 ( 7.6%)
	Quote ...................   959 (42.1%)
	Buy .....................   202 ( 8.9%)
	Sell ....................   192 ( 8.4%)
	Update ..................    25 ( 1.1%)
	Register ................    13 ( 0.6%)
	Login ...................   128 ( 5.6%)
	Logout ..................   141 ( 6.2%)
===== DaCapo 9.12-MR1 tradesoap PASSED in 20564 msec =====
Shutting down Geronimo...
```

xalan:

``` console
[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar xalan
Using scaled threading model. 2 processors detected, 2 threads used to drive the workload, in a possible range of [1,100]
===== DaCapo 9.12-MR1 xalan starting =====
Normal completion.
===== DaCapo 9.12-MR1 xalan PASSED in 3644 msec =====
```

**Comment by BigBrotherJu** [comment]
接下来，我们在 oe rv 上运行 DaCapo 的所有 benchmark。oe rv 通过 qemu 运行在 Ubuntu 20.04.3 LTS 中。qemu 的启动参数如下，给 oe rv 模拟了 4 个CPU，2G 内存：

``` console
$ qemu-system-riscv64 \
  -nographic -machine virt \
  -smp 4 -m 2G \
  -kernel fw_payload_oe.elf \
  -drive file=openEuler-preview.riscv64.qcow2,format=qcow2,id=hd0 \
  -object rng-random,filename=/dev/urandom,id=rng0 \
  -device virtio-rng-device,rng=rng0 \
  -device virtio-blk-device,drive=hd0 \
  -device virtio-net-device,netdev=usernet \
  -netdev user,id=usernet,hostfwd=tcp::12055-:22 \
  -append 'root=/dev/vda1 rw console=ttyS0 systemd.default_timeout_start_sec=600 selinux=0 highres=off earlycon'
```
qemu 的版本信息如下：

``` console
juhan@juhan-ubuntu:~$ qemu-system-riscv64 --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.19)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

MacBook Pro 2018 15 寸上的虚拟机，被分配了 4G 内存和 2 个 CPU。MacBook Pro 2018 15 寸本身的 CPU 是 i7-8750H，6 核 12 线程，内存一共 16 G。fedora 35 上的 jdk 如下所示：

[juhan@fedora dacapo]$ java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)
首先列出所有 benchmark：

[juhan@fedora dacapo]$ java -jar dacapo-9.12-MR1-bach.jar -l
avrora batik eclipse fop h2 jython luindex lusearch lusearch-fix pmd sunflow tomcat tradebeans tradesoap xalan

**Comment by BigBrotherJu** [comment]
现在我们可以及其不严谨地总结一下：

| Benchmark | Fedora 35 on AMD64 | OpenEuler on RISC-V 64 | 执行时间比值 |
| - | - | - | - |
| avrora | 5591 msec | 219269 msec | 39.22 |
| batik | 出错 | 出错 | N/A |
| eclipse | 出错 | 出错 | N/A |
| fop | 1607 msec | 98840 msec | 61.51 |
| h2 | 3968 msec | 140176 msec | 35.33 |
| jython | 7340 msec | 299832 msec | 40.85 |
| luindex | 1240 msec | 44438 msec | 35.84 |
| lusearch-fix | 2760 msec | 108513 msec | 39.32 |
| pmd | 2540 msec | 173512 msec | 68.31 |
| sunflow | 4067 msec | 99310 msec | 24.42 |
| tomcat | 出错 | 出错 | N/A |
| tradebeans | 6102 msec | 出错 | N/A |
| tradesoap | 20564 msec | 1037251 msec | 50.44 |
| xalan | 3644 msec | 207291 msec | 56.89 |

可以看到，跑在 qemu 中的 oe 花的时间基本上是 fedora 的 40 倍，有时甚至达到 60 倍。

**Comment by xijing21** [comment]
very good
操作与记录、分析与总结都做的很好。
